#!/usr/bin/env python3
"""Blind, deterministic solver for CUMCM 2016A (mooring-system design).

Only Python's standard library is used.  The script implements

1. a lumped single-link baseline;
2. a segmented rigid-link + massless straight-chain candidate; and
3. the selected segmented rigid-link + weighted catenary model.

All reported numbers and figures are regenerated by ``python code/solve.py``.
"""

from __future__ import print_function

import csv
import logging
logging.disable(logging.CRITICAL)
import hashlib
import json
import math
import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
FIGURES = ROOT / "figures"

G = 9.80665
RHO_WATER = 1025.0
RHO_STEEL = 7850.0
WIND_COEFF = 0.625
CURRENT_COEFF = 374.0
BUOY_DIAMETER = 2.0
BUOY_HEIGHT = 2.0
BUOY_AREA = math.pi * (BUOY_DIAMETER / 2.0) ** 2
BUOY_MASS = 1000.0
PIPE_COUNT = 4
PIPE_LENGTH = 1.0
PIPE_DIAMETER = 0.05
PIPE_MASS = 10.0
DRUM_LENGTH = 1.0
DRUM_DIAMETER = 0.30
DRUM_MASS = 100.0
BALL_DENSITY = RHO_STEEL

CHAIN_TYPES = {
    "I": {"link_length_m": 0.078, "linear_mass_kg_m": 3.2},
    "II": {"link_length_m": 0.105, "linear_mass_kg_m": 7.0},
    "III": {"link_length_m": 0.120, "linear_mass_kg_m": 12.5},
    "IV": {"link_length_m": 0.150, "linear_mass_kg_m": 19.5},
    "V": {"link_length_m": 0.180, "linear_mass_kg_m": 28.12},
}

MEMBERS_TOP_TO_BOTTOM = [
    {"name": "pipe_1", "length": PIPE_LENGTH, "diameter": PIPE_DIAMETER, "mass": PIPE_MASS},
    {"name": "pipe_2", "length": PIPE_LENGTH, "diameter": PIPE_DIAMETER, "mass": PIPE_MASS},
    {"name": "pipe_3", "length": PIPE_LENGTH, "diameter": PIPE_DIAMETER, "mass": PIPE_MASS},
    {"name": "pipe_4", "length": PIPE_LENGTH, "diameter": PIPE_DIAMETER, "mass": PIPE_MASS},
    {"name": "drum", "length": DRUM_LENGTH, "diameter": DRUM_DIAMETER, "mass": DRUM_MASS},
]


class InfeasibleError(RuntimeError):
    pass


def cylinder_volume(length, diameter):
    return math.pi * (diameter / 2.0) ** 2 * length


def member_weight(member, rho_water=RHO_WATER):
    """Submerged downward force; negative would denote net buoyancy."""
    displaced = cylinder_volume(member["length"], member["diameter"])
    return (member["mass"] - rho_water * displaced) * G


def ball_weight(ball_mass, rho_water=RHO_WATER, ball_density=BALL_DENSITY):
    return ball_mass * (1.0 - rho_water / ball_density) * G


def chain_weight_per_m(chain_type, rho_water=RHO_WATER):
    m = CHAIN_TYPES[chain_type]["linear_mass_kg_m"]
    return m * (1.0 - rho_water / RHO_STEEL) * G


def base_supported_mass(ball_mass, rho_water=RHO_WATER, ball_density=BALL_DENSITY):
    member_mass = sum(member_weight(m, rho_water) for m in MEMBERS_TOP_TO_BOTTOM) / G
    ball_mass_eff = ball_weight(ball_mass, rho_water, ball_density) / G
    return BUOY_MASS + member_mass + ball_mass_eff


def draft_from_vertical_tension(vertical_tension, ball_mass, rho_water=RHO_WATER,
                                ball_density=BALL_DENSITY):
    return (base_supported_mass(ball_mass, rho_water, ball_density) + vertical_tension / G) / (
        rho_water * BUOY_AREA
    )


def bisect_root(func, lo, hi, iterations=70, tol=1.0e-11):
    flo = func(lo)
    fhi = func(hi)
    if not (math.isfinite(flo) and math.isfinite(fhi)):
        raise InfeasibleError("non-finite root bracket")
    if flo == 0.0:
        return lo
    if fhi == 0.0:
        return hi
    if flo * fhi > 0.0:
        raise InfeasibleError("root is not bracketed: %.6g, %.6g" % (flo, fhi))
    for _ in range(iterations):
        mid = 0.5 * (lo + hi)
        fmid = func(mid)
        if abs(fmid) <= tol or (hi - lo) <= tol * max(1.0, abs(mid)):
            return mid
        if flo * fmid <= 0.0:
            hi = mid
            fhi = fmid
        else:
            lo = mid
            flo = fmid
    return 0.5 * (lo + hi)


def solve_member_angle(down_h, down_v, weight, drag_if_vertical):
    """Angle from vertical using a moment balance about the upper hinge.

    The member points down and upwind from its upper hinge.  Drag is applied at
    the midpoint and equals q*cos(alpha).  The scalar moment equation is

      (V + W/2) sin(alpha) - H cos(alpha) + q cos(alpha)^2/2 = 0.
    """
    a = down_v + 0.5 * weight

    def residual(alpha):
        c = math.cos(alpha)
        return a * math.sin(alpha) - down_h * c + 0.5 * drag_if_vertical * c * c

    # The drag term is small compared with the transmitted tension in all
    # admissible designs.  Newton's method is therefore both stable and much
    # faster than a nested 70-step bisection during design screening.
    alpha = math.atan2(down_h - 0.5 * drag_if_vertical, max(1.0e-12, a))
    alpha = max(-1.50, min(1.50, alpha))
    for _ in range(10):
        s = math.sin(alpha)
        c = math.cos(alpha)
        value = a * s - down_h * c + 0.5 * drag_if_vertical * c * c
        derivative = a * c + down_h * s - drag_if_vertical * c * s
        if abs(derivative) <= 1.0e-14:
            break
        updated = max(-1.55, min(1.55, alpha - value / derivative))
        if abs(updated - alpha) <= 1.0e-14:
            alpha = updated
            break
        alpha = updated
    if abs(residual(alpha)) > 1.0e-8:
        alpha = bisect_root(residual, -1.55, 1.55, iterations=60, tol=1.0e-13)
    return alpha


def buoy_horizontal_load(draft, wind_speed, current_speed, rho_water=RHO_WATER,
                         wind_coeff=WIND_COEFF, current_coeff=CURRENT_COEFF,
                         horizontal_factor=1.0):
    freeboard = max(0.0, BUOY_HEIGHT - draft)
    submerged = min(BUOY_HEIGHT, max(0.0, draft))
    wind = wind_coeff * BUOY_DIAMETER * freeboard * wind_speed ** 2
    current = current_coeff * BUOY_DIAMETER * submerged * current_speed ** 2
    return {
        "wind": horizontal_factor * wind,
        "current": horizontal_factor * current,
        "total": horizontal_factor * (wind + current),
    }


def compute_segmented_members(chain_h, chain_v, ball_mass, current_speed,
                              rho_water=RHO_WATER, current_coeff=CURRENT_COEFF,
                              horizontal_factor=1.0, ball_density=BALL_DENSITY):
    down_h = chain_h
    down_v = chain_v + ball_weight(ball_mass, rho_water, ball_density)
    bottom_up = []
    for member in reversed(MEMBERS_TOP_TO_BOTTOM):
        weight = member_weight(member, rho_water)
        q = horizontal_factor * current_coeff * member["diameter"] * member["length"] * current_speed ** 2
        angle = solve_member_angle(down_h, down_v, weight, q)
        drag = q * math.cos(angle)
        moment_residual = (
            (down_v + 0.5 * weight) * math.sin(angle)
            - down_h * math.cos(angle)
            + 0.5 * q * math.cos(angle) ** 2
        ) * member["length"]
        bottom_up.append({
            "name": member["name"],
            "length": member["length"],
            "diameter": member["diameter"],
            "net_weight_n": weight,
            "angle_rad": angle,
            "angle_deg": math.degrees(angle),
            "drag_n": drag,
            "downstream_h_n": down_h,
            "downstream_v_n": down_v,
            "moment_residual_nm": moment_residual,
        })
        down_h -= drag
        down_v += weight
    by_name = {row["name"]: row for row in bottom_up}
    ordered = [by_name[m["name"]] for m in MEMBERS_TOP_TO_BOTTOM]
    return {
        "members": ordered,
        "top_h_n": down_h,
        "top_v_n": down_v,
        "total_member_drag_n": sum(row["drag_n"] for row in ordered),
        "max_moment_residual_nm": max(abs(row["moment_residual_nm"]) for row in ordered),
    }


def solve_horizontal_for_vertical(chain_v, scenario, design, rho_water=RHO_WATER,
                                  wind_coeff=WIND_COEFF, current_coeff=CURRENT_COEFF,
                                  horizontal_factor=1.0, ball_density=BALL_DENSITY):
    draft = draft_from_vertical_tension(
        chain_v, design["ball_mass_kg"], rho_water, ball_density
    )
    loads = buoy_horizontal_load(
        draft, scenario["wind_m_s"], scenario["current_m_s"], rho_water,
        wind_coeff, current_coeff, horizontal_factor
    )
    q_sum = sum(
        horizontal_factor * current_coeff * m["diameter"] * m["length"] * scenario["current_m_s"] ** 2
        for m in MEMBERS_TOP_TO_BOTTOM
    )
    h_guess = loads["total"] + q_sum
    chain_h = max(0.0, h_guess)
    assembly = None
    for _ in range(30):
        assembly = compute_segmented_members(
            chain_h, chain_v, design["ball_mass_kg"], scenario["current_m_s"],
            rho_water, current_coeff, horizontal_factor, ball_density
        )
        target = loads["total"] + assembly["total_member_drag_n"]
        updated = target
        if abs(updated - chain_h) <= 1.0e-11 * max(1.0, target):
            chain_h = target
            break
        chain_h = updated
    assembly = compute_segmented_members(
        chain_h, chain_v, design["ball_mass_kg"], scenario["current_m_s"],
        rho_water, current_coeff, horizontal_factor, ball_density
    )
    target = loads["total"] + assembly["total_member_drag_n"]
    chain_h = target
    assembly = compute_segmented_members(
        chain_h, chain_v, design["ball_mass_kg"], scenario["current_m_s"],
        rho_water, current_coeff, horizontal_factor, ball_density
    )
    return draft, chain_h, loads, assembly


def chain_geometry(chain_h, chain_v, chain_length, weight_per_m):
    if chain_h < 0.0 or chain_v < 0.0:
        raise InfeasibleError("chain cannot carry negative end tension")
    tol = 1.0e-10 * max(1.0, weight_per_m * chain_length)
    if chain_v <= weight_per_m * chain_length + tol:
        suspended = min(chain_length, max(0.0, chain_v / weight_per_m))
        bottom_v = 0.0
        state = "seabed_contact"
        if chain_h <= 1.0e-14:
            rise = suspended
            suspended_x = 0.0
        else:
            rise = (math.hypot(chain_h, chain_v) - chain_h) / weight_per_m
            suspended_x = (chain_h / weight_per_m) * math.asinh(chain_v / chain_h)
        seabed_length = max(0.0, chain_length - suspended)
        span = seabed_length + suspended_x
        anchor_angle = 0.0
    else:
        suspended = chain_length
        bottom_v = chain_v - weight_per_m * chain_length
        state = "fully_suspended"
        seabed_length = 0.0
        if chain_h <= 1.0e-14:
            rise = chain_length
            suspended_x = 0.0
        else:
            rise = (
                math.hypot(chain_h, chain_v) - math.hypot(chain_h, bottom_v)
            ) / weight_per_m
            suspended_x = (chain_h / weight_per_m) * (
                math.asinh(chain_v / chain_h) - math.asinh(bottom_v / chain_h)
            )
        span = suspended_x
        anchor_angle = math.atan2(bottom_v, chain_h)
    return {
        "state": state,
        "rise_m": rise,
        "horizontal_span_m": span,
        "suspended_span_m": suspended_x,
        "seabed_length_m": seabed_length,
        "suspended_length_m": suspended,
        "bottom_vertical_tension_n": bottom_v,
        "anchor_angle_rad": anchor_angle,
        "anchor_angle_deg": math.degrees(anchor_angle),
        "top_tension_n": math.hypot(chain_h, chain_v),
        "bottom_tension_n": math.hypot(chain_h, bottom_v),
    }


def solve_case(scenario, design, rho_water=RHO_WATER, wind_coeff=WIND_COEFF,
               current_coeff=CURRENT_COEFF, horizontal_factor=1.0,
               ball_density=BALL_DENSITY, vertical_iterations=55):
    chain_type = design["chain_type"]
    chain_length = design["chain_length_m"]
    w = chain_weight_per_m(chain_type, rho_water)
    base_mass = base_supported_mass(design["ball_mass_kg"], rho_water, ball_density)
    vertical_cap = (rho_water * BUOY_AREA * BUOY_HEIGHT - base_mass) * G
    if vertical_cap <= 0.0:
        raise InfeasibleError("dry/effective supported mass submerges the buoy")

    def state_for_v(chain_v):
        draft, chain_h, loads, assembly = solve_horizontal_for_vertical(
            chain_v, scenario, design, rho_water, wind_coeff, current_coeff,
            horizontal_factor, ball_density
        )
        vertical_projection = sum(
            row["length"] * math.cos(row["angle_rad"]) for row in assembly["members"]
        )
        top_height = scenario["depth_m"] - draft - vertical_projection
        geometry = chain_geometry(chain_h, chain_v, chain_length, w)
        return geometry["rise_m"] - top_height, draft, chain_h, loads, assembly, top_height, geometry

    lo = 0.0
    hi = vertical_cap * (1.0 - 1.0e-9)
    flo = state_for_v(lo)[0]
    fhi = state_for_v(hi)[0]
    if flo > 0.0:
        raise InfeasibleError("chain endpoint is below the seabed at zero vertical tension")
    if fhi < 0.0:
        raise InfeasibleError("insufficient buoyancy/chain length for vertical geometry")
    chain_v = bisect_root(
        lambda value: state_for_v(value)[0], lo, hi,
        iterations=vertical_iterations,
        tol=1.0e-10 if vertical_iterations >= 50 else 1.0e-7,
    )
    residual, draft, chain_h, loads, assembly, top_height, geometry = state_for_v(chain_v)
    horizontal_member_offset = sum(
        row["length"] * math.sin(row["angle_rad"]) for row in assembly["members"]
    )
    radius = geometry["horizontal_span_m"] + horizontal_member_offset
    drum = next(row for row in assembly["members"] if row["name"] == "drum")
    horizontal_force_residual = chain_h - loads["total"] - assembly["total_member_drag_n"]
    vertical_force_residual = (
        rho_water * G * BUOY_AREA * draft
        - base_supported_mass(design["ball_mass_kg"], rho_water, ball_density) * G
        - chain_v
    )
    return {
        "scenario": dict(scenario),
        "design": dict(design),
        "draft_m": draft,
        "freeboard_m": BUOY_HEIGHT - draft,
        "chain_horizontal_tension_n": chain_h,
        "chain_vertical_tension_n": chain_v,
        "buoy_wind_force_n": loads["wind"],
        "buoy_current_force_n": loads["current"],
        "member_current_force_n": assembly["total_member_drag_n"],
        "total_horizontal_force_n": chain_h,
        "members": assembly["members"],
        "drum_angle_deg": drum["angle_deg"],
        "chain": geometry,
        "chain_top_height_m": top_height,
        "member_horizontal_offset_m": horizontal_member_offset,
        "wander_radius_m": radius,
        "wander_area_m2": math.pi * radius * radius,
        "constraints": {
            "drum_angle_le_5": "pass" if drum["angle_deg"] <= 5.0 + 1.0e-8 else "fail",
            "anchor_angle_le_16": "pass" if geometry["anchor_angle_deg"] <= 16.0 + 1.0e-8 else "fail",
            "draft_in_0_2": "pass" if 0.0 < draft < 2.0 else "fail",
        },
        "residuals": {
            "chain_vertical_geometry_m": residual,
            "horizontal_force_n": horizontal_force_residual,
            "vertical_force_n": vertical_force_residual,
            "max_member_moment_nm": assembly["max_moment_residual_nm"],
        },
        "settings": {
            "rho_water_kg_m3": rho_water,
            "ball_density_kg_m3": ball_density,
            "wind_coeff": wind_coeff,
            "current_coeff": current_coeff,
            "horizontal_factor": horizontal_factor,
            "chain_current_drag_included": False,
        },
    }


def solve_lumped_baseline(scenario, design):
    """Simple baseline: all five rigid components form one equivalent link."""
    w_chain = chain_weight_per_m(design["chain_type"])
    w_members = sum(member_weight(m) for m in MEMBERS_TOP_TO_BOTTOM)
    w_ball = ball_weight(design["ball_mass_kg"])
    q_total = sum(
        CURRENT_COEFF * m["diameter"] * m["length"] * scenario["current_m_s"] ** 2
        for m in MEMBERS_TOP_TO_BOTTOM
    )
    base_mass = base_supported_mass(design["ball_mass_kg"])
    cap = (RHO_WATER * BUOY_AREA * BUOY_HEIGHT - base_mass) * G * (1.0 - 1.0e-9)

    def state(chain_v):
        draft = draft_from_vertical_tension(chain_v, design["ball_mass_kg"])
        loads = buoy_horizontal_load(draft, scenario["wind_m_s"], scenario["current_m_s"])
        hval = loads["total"] + q_total
        alpha = 0.0
        for _ in range(60):
            drag = q_total * math.cos(alpha)
            hnew = loads["total"] + drag
            alpha_new = math.atan2(max(0.0, hnew - 0.5 * drag), chain_v + w_ball + 0.5 * w_members)
            if abs(alpha_new - alpha) < 1.0e-13 and abs(hnew - hval) < 1.0e-10:
                hval = hnew
                alpha = alpha_new
                break
            hval = 0.5 * hval + 0.5 * hnew
            alpha = 0.5 * alpha + 0.5 * alpha_new
        geom = chain_geometry(hval, chain_v, design["chain_length_m"], w_chain)
        top_height = scenario["depth_m"] - draft - 5.0 * math.cos(alpha)
        return geom["rise_m"] - top_height, draft, hval, alpha, geom

    chain_v = bisect_root(lambda v: state(v)[0], 0.0, cap, iterations=65, tol=1.0e-10)
    residual, draft, chain_h, alpha, geom = state(chain_v)
    radius = geom["horizontal_span_m"] + 5.0 * math.sin(alpha)
    return {
        "model": "lumped_single_link_baseline",
        "draft_m": draft,
        "drum_angle_deg": math.degrees(alpha),
        "anchor_angle_deg": geom["anchor_angle_deg"],
        "wander_radius_m": radius,
        "chain_state": geom["state"],
        "vertical_geometry_residual_m": residual,
    }


def solve_massless_taut_candidate(scenario, design):
    """Rejected candidate: segmented members but a straight, weightless chain."""
    base_mass = base_supported_mass(design["ball_mass_kg"])
    cap = (RHO_WATER * BUOY_AREA * BUOY_HEIGHT - base_mass) * G * (1.0 - 1.0e-9)

    def state(chain_v):
        draft, chain_h, loads, assembly = solve_horizontal_for_vertical(chain_v, scenario, design)
        top_height = scenario["depth_m"] - draft - sum(
            row["length"] * math.cos(row["angle_rad"]) for row in assembly["members"]
        )
        if top_height >= design["chain_length_m"]:
            return -1.0e6, None
        span = math.sqrt(max(1.0e-16, design["chain_length_m"] ** 2 - top_height ** 2))
        required_v = chain_h * top_height / span
        return chain_v - required_v, (draft, chain_h, assembly, top_height, span)

    chain_v = bisect_root(lambda v: state(v)[0], 0.0, cap, iterations=65, tol=1.0e-10)
    residual, payload = state(chain_v)
    draft, chain_h, assembly, top_height, span = payload
    drum = next(row for row in assembly["members"] if row["name"] == "drum")
    offset = sum(row["length"] * math.sin(row["angle_rad"]) for row in assembly["members"])
    return {
        "model": "segmented_massless_straight_chain",
        "draft_m": draft,
        "drum_angle_deg": drum["angle_deg"],
        "anchor_angle_deg": math.degrees(math.atan2(top_height, span)),
        "wander_radius_m": span + offset,
        "chain_state": "straight_by_assumption",
        "vertical_geometry_residual_m": residual,
    }


def chain_profile(case, n=121):
    chain_h = case["chain_horizontal_tension_n"]
    chain_v = case["chain_vertical_tension_n"]
    chain_type = case["design"]["chain_type"]
    length = case["design"]["chain_length_m"]
    w = chain_weight_per_m(chain_type, case["settings"]["rho_water_kg_m3"])
    geom = case["chain"]
    points = []
    if geom["state"] == "seabed_contact":
        seabed = geom["seabed_length_m"]
        points.append((0.0, 0.0, "chain"))
        if seabed > 0.0:
            points.append((seabed, 0.0, "chain"))
        suspended = geom["suspended_length_m"]
        for idx in range(1, n + 1):
            s = suspended * idx / n
            if chain_h <= 1.0e-14:
                x = seabed
                z = s
            else:
                x = seabed + (chain_h / w) * math.asinh(w * s / chain_h)
                z = (math.hypot(chain_h, w * s) - chain_h) / w
            points.append((x, z, "chain"))
    else:
        bottom_v = geom["bottom_vertical_tension_n"]
        for idx in range(n + 1):
            s = length * idx / n
            if chain_h <= 1.0e-14:
                x = 0.0
                z = s
            else:
                x = (chain_h / w) * (
                    math.asinh((bottom_v + w * s) / chain_h)
                    - math.asinh(bottom_v / chain_h)
                )
                z = (
                    math.hypot(chain_h, bottom_v + w * s)
                    - math.hypot(chain_h, bottom_v)
                ) / w
            points.append((x, z, "chain"))
    x = points[-1][0]
    z = points[-1][1]
    for row in reversed(case["members"]):
        x += row["length"] * math.sin(row["angle_rad"])
        z += row["length"] * math.cos(row["angle_rad"])
        points.append((x, z, row["name"]))
    return points


def numeric_chain_endpoint(case, n=20000):
    """Independent midpoint quadrature of the catenary tangent equations."""
    h = case["chain_horizontal_tension_n"]
    vtop = case["chain_vertical_tension_n"]
    length = case["design"]["chain_length_m"]
    w = chain_weight_per_m(case["design"]["chain_type"], case["settings"]["rho_water_kg_m3"])
    geom = case["chain"]
    if geom["state"] == "seabed_contact":
        suspended = geom["suspended_length_m"]
        bottom_v = 0.0
        x = geom["seabed_length_m"]
    else:
        suspended = length
        bottom_v = vtop - w * length
        x = 0.0
    z = 0.0
    if suspended <= 0.0:
        return x, z
    ds = suspended / n
    for idx in range(n):
        s = (idx + 0.5) * ds
        vv = bottom_v + w * s
        tension = math.hypot(h, vv)
        if tension <= 1.0e-20:
            continue
        x += h / tension * ds
        z += vv / tension * ds
    return x, z


def round_up(value, quantum):
    return math.ceil((value - 1.0e-12) / quantum) * quantum


def case_constraint_ratio(case):
    return max(case["drum_angle_deg"] / 5.0, case["chain"]["anchor_angle_deg"] / 16.0)


def design_envelope(design, horizontal_factor=1.0, vertical_iterations=55):
    cases = []
    for depth in (16.0, 18.0, 20.0):
        scenario = {"id": "D%02d-W36-C15" % int(depth), "depth_m": depth,
                    "wind_m_s": 36.0, "current_m_s": 1.5}
        cases.append(solve_case(
            scenario, design, horizontal_factor=horizontal_factor,
            vertical_iterations=vertical_iterations,
        ))
    return cases


def screening_envelope(design, horizontal_factor=1.10):
    """Depth endpoints suffice for screening; the selected design is later
    recomputed at 16, 18 and 20 m with the strict solver."""
    cases = []
    for depth in (16.0, 20.0):
        scenario = {"id": "SCREEN-D%02d" % int(depth), "depth_m": depth,
                    "wind_m_s": 36.0, "current_m_s": 1.5}
        cases.append(solve_case(
            scenario, design, horizontal_factor=horizontal_factor,
            vertical_iterations=27,
        ))
    return cases


def metrics(cases):
    return {
        "max_draft_m": max(c["draft_m"] for c in cases),
        "max_drum_angle_deg": max(c["drum_angle_deg"] for c in cases),
        "max_anchor_angle_deg": max(c["chain"]["anchor_angle_deg"] for c in cases),
        "max_wander_radius_m": max(c["wander_radius_m"] for c in cases),
    }


def find_min_ball_for_design(chain_type, chain_length, stress_factor=1.10):
    last_mass = 500.0
    last_ratio = float("inf")
    bracket = None
    for mass in [500.0 + 400.0 * i for i in range(13)]:
        design = {"chain_type": chain_type, "chain_length_m": chain_length, "ball_mass_kg": mass}
        try:
            cases = screening_envelope(design, horizontal_factor=stress_factor)
            ratio = max(case_constraint_ratio(c) for c in cases)
            draft_ok = max(c["draft_m"] for c in cases) < 2.0
        except InfeasibleError:
            ratio = float("inf")
            draft_ok = False
        if ratio <= 1.0 and draft_ok:
            bracket = (last_mass, mass)
            break
        last_mass = mass
        last_ratio = ratio
    if bracket is None:
        return None

    def margin(mass):
        design = {"chain_type": chain_type, "chain_length_m": chain_length, "ball_mass_kg": mass}
        try:
            cases = screening_envelope(design, horizontal_factor=stress_factor)
        except InfeasibleError:
            return 1.0e6
        return max(case_constraint_ratio(c) for c in cases) - 1.0

    lo, hi = bracket
    if margin(lo) <= 0.0:
        threshold = lo
    else:
        threshold = bisect_root(margin, lo, hi, iterations=18, tol=1.0e-5)
    recommended = round_up(threshold, 50.0)
    design = {"chain_type": chain_type, "chain_length_m": chain_length, "ball_mass_kg": recommended}
    stressed_cases = screening_envelope(design, horizontal_factor=stress_factor)
    nominal_cases = screening_envelope(design, horizontal_factor=1.0)
    if max(case_constraint_ratio(c) for c in stressed_cases) > 1.0 + 1.0e-7:
        return None
    return {
        "chain_type": chain_type,
        "link_count": int(round(chain_length / CHAIN_TYPES[chain_type]["link_length_m"])),
        "chain_length_m": chain_length,
        "chain_dry_mass_kg": chain_length * CHAIN_TYPES[chain_type]["linear_mass_kg_m"],
        "continuous_ball_threshold_kg": threshold,
        "ball_mass_kg": recommended,
        "stress_factor": stress_factor,
        "nominal": metrics(nominal_cases),
        "stressed": metrics(stressed_cases),
    }


def pareto_front(rows):
    objectives = ("max_draft_m", "max_drum_angle_deg", "max_wander_radius_m")
    front = []
    for i, row in enumerate(rows):
        dominated = False
        ai = row["nominal"]
        for j, other in enumerate(rows):
            if i == j:
                continue
            aj = other["nominal"]
            no_worse = all(aj[key] <= ai[key] + 1.0e-12 for key in objectives)
            strictly = any(aj[key] < ai[key] - 1.0e-12 for key in objectives)
            if no_worse and strictly:
                dominated = True
                break
        if not dominated:
            front.append(row)
    return front


def select_knee(front):
    # Fixed, problem-defined scales avoid allowing a very narrow observed range
    # (for example a few hundredths of a degree) to dominate metres of wander.
    scales = {"max_draft_m": 2.0, "max_drum_angle_deg": 5.0,
              "max_wander_radius_m": 20.0}
    best = None
    best_score = float("inf")
    for row in front:
        components = [row["nominal"][key] / scale for key, scale in scales.items()]
        score = math.sqrt(sum(value * value for value in components))
        row["compromise_score"] = score
        if score < best_score - 1.0e-12:
            best_score = score
            best = row
        elif abs(score - best_score) <= 1.0e-12:
            tie_new = (row["chain_dry_mass_kg"], row["chain_length_m"], row["ball_mass_kg"])
            tie_old = (best["chain_dry_mass_kg"], best["chain_length_m"], best["ball_mass_kg"])
            if tie_new < tie_old:
                best = row
    return best


def write_csv(path, rows, fieldnames=None):
    path.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None:
        fieldnames = list(rows[0].keys()) if rows else []
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def write_json(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(value, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")


COLORS = ["#1f77b4", "#d62728", "#2ca02c", "#9467bd", "#ff7f0e", "#17becf"]


def escape_xml(text):
    return str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def pdf_escape(text):
    return str(text).replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def hex_to_rgb(color):
    color = color.lstrip("#")
    return tuple(int(color[i:i + 2], 16) / 255.0 for i in (0, 2, 4))


def make_plot_payload(series, x_label, y_label, title, refs=None, scatter=False):
    xs = [x for item in series for x, _ in item["points"]]
    ys = [y for item in series for _, y in item["points"]]
    if refs:
        ys.extend(value for value, _ in refs)
    xmin, xmax = min(xs), max(xs)
    ymin, ymax = min(ys), max(ys)
    if xmax <= xmin:
        xmax = xmin + 1.0
    if ymax <= ymin:
        ymax = ymin + 1.0
    xpad = 0.05 * (xmax - xmin)
    ypad = 0.10 * (ymax - ymin)
    return {
        "series": series,
        "x_label": x_label,
        "y_label": y_label,
        "title": title,
        "refs": refs or [],
        "scatter": scatter,
        "xmin": xmin - xpad,
        "xmax": xmax + xpad,
        "ymin": max(0.0, ymin - ypad) if ymin >= 0.0 else ymin - ypad,
        "ymax": ymax + ypad,
    }


def write_svg_plot(path, payload, width=720, height=480):
    left, right, top, bottom = 80.0, 28.0, 52.0, 68.0
    pw, ph = width - left - right, height - top - bottom

    def px(x):
        return left + (x - payload["xmin"]) / (payload["xmax"] - payload["xmin"]) * pw

    def py(y):
        return top + (payload["ymax"] - y) / (payload["ymax"] - payload["ymin"]) * ph

    out = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d">' % (width, height, width, height),
        '<rect width="100%%" height="100%%" fill="white"/>',
        '<style>text{font-family:Arial,Helvetica,sans-serif;fill:#222}.tick{font-size:11px}.label{font-size:13px}.title{font-size:17px;font-weight:600}.legend{font-size:11px}</style>',
        '<text class="title" x="%g" y="27" text-anchor="middle">%s</text>' % (width / 2.0, escape_xml(payload["title"])),
    ]
    for idx in range(6):
        xv = payload["xmin"] + idx * (payload["xmax"] - payload["xmin"]) / 5.0
        yv = payload["ymin"] + idx * (payload["ymax"] - payload["ymin"]) / 5.0
        out.append('<line x1="%g" y1="%g" x2="%g" y2="%g" stroke="#e6e6e6"/>' % (px(xv), top, px(xv), top + ph))
        out.append('<line x1="%g" y1="%g" x2="%g" y2="%g" stroke="#e6e6e6"/>' % (left, py(yv), left + pw, py(yv)))
        out.append('<text class="tick" x="%g" y="%g" text-anchor="middle">%.3g</text>' % (px(xv), top + ph + 20, xv))
        out.append('<text class="tick" x="%g" y="%g" text-anchor="end">%.3g</text>' % (left - 8, py(yv) + 4, yv))
    out.append('<line x1="%g" y1="%g" x2="%g" y2="%g" stroke="#222" stroke-width="1.4"/>' % (left, top + ph, left + pw, top + ph))
    out.append('<line x1="%g" y1="%g" x2="%g" y2="%g" stroke="#222" stroke-width="1.4"/>' % (left, top, left, top + ph))
    for value, label in payload["refs"]:
        out.append('<line x1="%g" y1="%g" x2="%g" y2="%g" stroke="#555" stroke-dasharray="6,4"/>' % (left, py(value), left + pw, py(value)))
        out.append('<text class="legend" x="%g" y="%g" text-anchor="end">%s</text>' % (left + pw - 4, py(value) - 4, escape_xml(label)))
    for idx, item in enumerate(payload["series"]):
        color = item.get("color", COLORS[idx % len(COLORS)])
        coords = " ".join("%g,%g" % (px(x), py(y)) for x, y in item["points"])
        if not payload["scatter"]:
            out.append('<polyline points="%s" fill="none" stroke="%s" stroke-width="2.2"/>' % (coords, color))
        for x, y in item["points"]:
            out.append('<circle cx="%g" cy="%g" r="3.2" fill="%s"/>' % (px(x), py(y), color))
        lx = left + 12 + (idx % 3) * 190
        ly = top + 16 + (idx // 3) * 18
        out.append('<line x1="%g" y1="%g" x2="%g" y2="%g" stroke="%s" stroke-width="2.2"/>' % (lx, ly - 4, lx + 20, ly - 4, color))
        out.append('<text class="legend" x="%g" y="%g">%s</text>' % (lx + 25, ly, escape_xml(item["label"])))
    out.append('<text class="label" x="%g" y="%g" text-anchor="middle">%s</text>' % (left + pw / 2.0, height - 18, escape_xml(payload["x_label"])))
    out.append('<text class="label" transform="translate(18,%g) rotate(-90)" text-anchor="middle">%s</text>' % (top + ph / 2.0, escape_xml(payload["y_label"])))
    out.append('</svg>')
    path.write_text("\n".join(out) + "\n", encoding="utf-8")


def write_pdf_plot(path, payload, width=720, height=480):
    left, right, top, bottom = 80.0, 28.0, 52.0, 68.0
    pw, ph = width - left - right, height - top - bottom

    def px(x):
        return left + (x - payload["xmin"]) / (payload["xmax"] - payload["xmin"]) * pw

    def py(y):
        return bottom + (y - payload["ymin"]) / (payload["ymax"] - payload["ymin"]) * ph

    commands = ["1 1 1 rg 0 0 %d %d re f" % (width, height), "0 0 0 RG 0 0 0 rg"]

    def text_cmd(x, y, size, value):
        commands.append("BT /F1 %g Tf %g %g Td (%s) Tj ET" % (size, x, y, pdf_escape(value)))

    text_cmd(width / 2.0 - 120.0, height - 28.0, 16, payload["title"])
    for idx in range(6):
        xv = payload["xmin"] + idx * (payload["xmax"] - payload["xmin"]) / 5.0
        yv = payload["ymin"] + idx * (payload["ymax"] - payload["ymin"]) / 5.0
        commands.append("0.9 0.9 0.9 RG 0.5 w %g %g m %g %g l S" % (px(xv), bottom, px(xv), bottom + ph))
        commands.append("0.9 0.9 0.9 RG 0.5 w %g %g m %g %g l S" % (left, py(yv), left + pw, py(yv)))
        commands.append("0 0 0 RG")
        text_cmd(px(xv) - 13.0, bottom - 18.0, 9, "%.3g" % xv)
        text_cmd(left - 45.0, py(yv) - 3.0, 9, "%.3g" % yv)
    commands.append("0 0 0 RG 1.2 w %g %g m %g %g l S" % (left, bottom, left + pw, bottom))
    commands.append("0 0 0 RG 1.2 w %g %g m %g %g l S" % (left, bottom, left, bottom + ph))
    for value, label in payload["refs"]:
        yy = py(value)
        commands.append("0.35 0.35 0.35 RG [6 4] 0 d %g %g m %g %g l S [] 0 d" % (left, yy, left + pw, yy))
        text_cmd(left + pw - 92.0, yy + 4.0, 9, label)
    for idx, item in enumerate(payload["series"]):
        color = item.get("color", COLORS[idx % len(COLORS)])
        r, g, b = hex_to_rgb(color)
        commands.append("%g %g %g RG %g %g %g rg 2 w" % (r, g, b, r, g, b))
        if not payload["scatter"] and item["points"]:
            x0, y0 = item["points"][0]
            commands.append("%g %g m" % (px(x0), py(y0)))
            for x, y in item["points"][1:]:
                commands.append("%g %g l" % (px(x), py(y)))
            commands.append("S")
        for x, y in item["points"]:
            commands.append("%g %g 5 5 re f" % (px(x) - 2.5, py(y) - 2.5))
        lx = left + 12 + (idx % 3) * 190
        ly = bottom + ph - 16 - (idx // 3) * 17
        commands.append("%g %g m %g %g l S" % (lx, ly, lx + 20, ly))
        commands.append("0 0 0 rg")
        text_cmd(lx + 25, ly - 3, 9, item["label"])
    commands.append("0 0 0 rg")
    text_cmd(left + pw / 2.0 - 45.0, 18.0, 11, payload["x_label"])
    text_cmd(8.0, bottom + ph / 2.0, 10, payload["y_label"])
    stream = ("\n".join(commands) + "\n").encode("ascii", "replace")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        ("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 %d %d] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>" % (width, height)).encode("ascii"),
        b"<< /Length " + str(len(stream)).encode("ascii") + b" >>\nstream\n" + stream + b"endstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    blob = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(blob))
        blob.extend(("%d 0 obj\n" % index).encode("ascii"))
        blob.extend(obj)
        blob.extend(b"\nendobj\n")
    xref = len(blob)
    blob.extend(("xref\n0 %d\n" % (len(objects) + 1)).encode("ascii"))
    blob.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        blob.extend(("%010d 00000 n \n" % offset).encode("ascii"))
    blob.extend(("trailer << /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (len(objects) + 1, xref)).encode("ascii"))
    path.write_bytes(bytes(blob))


def emit_plot(name, series, x_label, y_label, title, refs=None, scatter=False):
    payload = make_plot_payload(series, x_label, y_label, title, refs, scatter)
    write_svg_plot(FIGURES / (name + ".svg"), payload)
    write_pdf_plot(FIGURES / (name + ".pdf"), payload)


def flatten_case(case, label):
    angles = {m["name"]: m["angle_deg"] for m in case["members"]}
    return {
        "case": label,
        "depth_m": case["scenario"]["depth_m"],
        "wind_m_s": case["scenario"]["wind_m_s"],
        "current_m_s": case["scenario"]["current_m_s"],
        "draft_m": case["draft_m"],
        "freeboard_m": case["freeboard_m"],
        "pipe_1_deg": angles["pipe_1"],
        "pipe_2_deg": angles["pipe_2"],
        "pipe_3_deg": angles["pipe_3"],
        "pipe_4_deg": angles["pipe_4"],
        "drum_deg": angles["drum"],
        "chain_state": case["chain"]["state"],
        "seabed_chain_m": case["chain"]["seabed_length_m"],
        "anchor_angle_deg": case["chain"]["anchor_angle_deg"],
        "chain_top_height_m": case["chain_top_height_m"],
        "chain_horizontal_span_m": case["chain"]["horizontal_span_m"],
        "wander_radius_m": case["wander_radius_m"],
        "wander_area_m2": case["wander_area_m2"],
        "chain_h_n": case["chain_horizontal_tension_n"],
        "chain_v_n": case["chain_vertical_tension_n"],
        "total_horizontal_force_n": case["total_horizontal_force_n"],
        "drum_constraint": case["constraints"]["drum_angle_le_5"],
        "anchor_constraint": case["constraints"]["anchor_angle_le_16"],
    }


def main():
    RESULTS.mkdir(parents=True, exist_ok=True)
    FIGURES.mkdir(parents=True, exist_ok=True)

    fixed_design = {"chain_type": "II", "chain_length_m": 22.05, "ball_mass_kg": 1200.0}
    q1_cases = []
    for wind in (12.0, 24.0):
        scenario = {"id": "Q1-W%02d" % int(wind), "depth_m": 18.0,
                    "wind_m_s": wind, "current_m_s": 0.0}
        q1_cases.append(solve_case(scenario, fixed_design))

    q2_scenario = {"id": "Q2-W36", "depth_m": 18.0, "wind_m_s": 36.0, "current_m_s": 0.0}
    q2_initial = solve_case(q2_scenario, fixed_design)

    def q2_margin(mass):
        design = dict(fixed_design)
        design["ball_mass_kg"] = mass
        case = solve_case(q2_scenario, design)
        return max(case["drum_angle_deg"] / 5.0, case["chain"]["anchor_angle_deg"] / 16.0) - 1.0

    q2_threshold = bisect_root(q2_margin, 1200.0, 4000.0, iterations=50, tol=1.0e-9)
    q2_recommended_mass = round_up(q2_threshold, 50.0)
    q2_design = dict(fixed_design)
    q2_design["ball_mass_kg"] = q2_recommended_mass
    q2_recommended = solve_case(q2_scenario, q2_design)
    q2_sweep = []
    for mass in range(1200, 3201, 100):
        design = dict(fixed_design)
        design["ball_mass_kg"] = float(mass)
        case = solve_case(q2_scenario, design)
        q2_sweep.append({
            "ball_mass_kg": mass,
            "draft_m": case["draft_m"],
            "drum_angle_deg": case["drum_angle_deg"],
            "anchor_angle_deg": case["chain"]["anchor_angle_deg"],
            "wander_radius_m": case["wander_radius_m"],
        })

    candidate_rows = []
    seen = set()
    for chain_type, params in CHAIN_TYPES.items():
        for idx in range(int(round((32.0 - 18.0) / 0.50)) + 1):
            target = 18.0 + 0.50 * idx
            links = max(1, int(round(target / params["link_length_m"])))
            length = links * params["link_length_m"]
            key = (chain_type, links)
            if key in seen:
                continue
            seen.add(key)
            candidate = find_min_ball_for_design(chain_type, length, stress_factor=1.10)
            if candidate is not None:
                candidate_rows.append(candidate)
    if not candidate_rows:
        raise RuntimeError("design search found no feasible candidate")
    front = pareto_front(candidate_rows)
    selected = select_knee(front)
    selected_design = {
        "chain_type": selected["chain_type"],
        "chain_length_m": selected["chain_length_m"],
        "ball_mass_kg": selected["ball_mass_kg"],
    }

    q3_cases = []
    for depth in (16.0, 18.0, 20.0):
        for wind in (0.0, 12.0, 24.0, 36.0):
            for current in (0.0, 0.75, 1.5):
                if wind == 0.0 and current == 0.0:
                    # With no horizontal forcing, azimuth and slack-chain
                    # layout are non-unique; do not report a spurious radius.
                    continue
                scenario = {
                    "id": "Q3-D%02d-W%02d-C%03d" % (int(depth), int(wind), int(round(current * 100))),
                    "depth_m": depth,
                    "wind_m_s": wind,
                    "current_m_s": current,
                }
                q3_cases.append(solve_case(scenario, selected_design))
    q3_stress_cases = design_envelope(selected_design, horizontal_factor=1.10)

    model_comparison = []
    comparison_cases = q1_cases + [q2_initial]
    for case in comparison_cases:
        scenario = case["scenario"]
        label = scenario["id"]
        baseline = solve_lumped_baseline(scenario, fixed_design)
        straight = solve_massless_taut_candidate(scenario, fixed_design)
        main_row = {
            "model": "segmented_weighted_catenary_selected",
            "draft_m": case["draft_m"],
            "drum_angle_deg": case["drum_angle_deg"],
            "anchor_angle_deg": case["chain"]["anchor_angle_deg"],
            "wander_radius_m": case["wander_radius_m"],
            "chain_state": case["chain"]["state"],
        }
        for row in (baseline, straight, main_row):
            out = {"case": label}
            out.update(row)
            model_comparison.append(out)

    validation_cases = [("q1_w12", q1_cases[0]), ("q1_w24", q1_cases[1]),
                        ("q2_initial", q2_initial), ("q2_recommended", q2_recommended)]
    worst_drum = max(q3_cases, key=lambda c: c["drum_angle_deg"])
    worst_anchor = max(q3_cases, key=lambda c: c["chain"]["anchor_angle_deg"])
    worst_radius = max(q3_cases, key=lambda c: c["wander_radius_m"])
    validation_cases.extend([("q3_worst_drum", worst_drum), ("q3_worst_anchor", worst_anchor),
                             ("q3_worst_radius", worst_radius)])
    validation_rows = []
    for label, case in validation_cases:
        num_x, num_z = numeric_chain_endpoint(case)
        validation_rows.append({
            "case": label,
            "horizontal_force_residual_n": case["residuals"]["horizontal_force_n"],
            "vertical_force_residual_n": case["residuals"]["vertical_force_n"],
            "chain_geometry_residual_m": case["residuals"]["chain_vertical_geometry_m"],
            "max_member_moment_residual_nm": case["residuals"]["max_member_moment_nm"],
            "quadrature_x_error_m": num_x - case["chain"]["horizontal_span_m"],
            "quadrature_z_error_m": num_z - case["chain"]["rise_m"],
        })
    validation_status = "pass" if all(
        abs(row["horizontal_force_residual_n"]) < 1.0e-6
        and abs(row["vertical_force_residual_n"]) < 1.0e-6
        and abs(row["chain_geometry_residual_m"]) < 1.0e-8
        and abs(row["max_member_moment_residual_nm"]) < 1.0e-6
        and abs(row["quadrature_x_error_m"]) < 1.0e-7
        and abs(row["quadrature_z_error_m"]) < 1.0e-7
        for row in validation_rows
    ) else "fail"

    sensitivity_rows = []
    worst_scenario = {"id": "SENS-D20-W36-C15", "depth_m": 20.0,
                      "wind_m_s": 36.0, "current_m_s": 1.5}
    for parameter, values in (
        ("rho_water_kg_m3", (1000.0, 1025.0, 1050.0)),
        ("ball_density_kg_m3", (3000.0, 7000.0, 7850.0, 8500.0)),
        ("horizontal_factor", (0.9, 1.0, 1.1, 1.2)),
    ):
        for value in values:
            kwargs = {"rho_water": RHO_WATER, "ball_density": BALL_DENSITY, "horizontal_factor": 1.0}
            if parameter == "rho_water_kg_m3":
                kwargs["rho_water"] = value
            elif parameter == "ball_density_kg_m3":
                kwargs["ball_density"] = value
            else:
                kwargs["horizontal_factor"] = value
            case = solve_case(worst_scenario, selected_design, **kwargs)
            sensitivity_rows.append({
                "parameter": parameter,
                "value": value,
                "draft_m": case["draft_m"],
                "drum_angle_deg": case["drum_angle_deg"],
                "anchor_angle_deg": case["chain"]["anchor_angle_deg"],
                "wander_radius_m": case["wander_radius_m"],
                "drum_constraint": case["constraints"]["drum_angle_le_5"],
                "anchor_constraint": case["constraints"]["anchor_angle_le_16"],
            })

    q1_rows = [flatten_case(case, case["scenario"]["id"]) for case in q1_cases]
    q2_rows = [
        flatten_case(q2_initial, "initial_1200kg"),
        flatten_case(q2_recommended, "recommended_%.0fkg" % q2_recommended_mass),
    ]
    q2_rows[0]["continuous_threshold_kg"] = q2_threshold
    q2_rows[1]["continuous_threshold_kg"] = q2_threshold
    q3_rows = [flatten_case(case, case["scenario"]["id"]) for case in q3_cases]

    write_csv(RESULTS / "<SOURCE_FILE_REDACTED>", q1_rows)
    write_csv(RESULTS / "<SOURCE_FILE_REDACTED>", q2_rows)
    write_csv(RESULTS / "<SOURCE_FILE_REDACTED>", q2_sweep)
    write_csv(RESULTS / "<SOURCE_FILE_REDACTED>", q3_rows)
    write_csv(RESULTS / "<SOURCE_FILE_REDACTED>", model_comparison)
    write_csv(RESULTS / "<SOURCE_FILE_REDACTED>", sensitivity_rows)
    write_csv(RESULTS / "<SOURCE_FILE_REDACTED>", validation_rows)

    candidate_flat = []
    for row in candidate_rows:
        candidate_flat.append({
            "chain_type": row["chain_type"], "link_count": row["link_count"],
            "chain_length_m": row["chain_length_m"], "chain_dry_mass_kg": row["chain_dry_mass_kg"],
            "ball_threshold_kg": row["continuous_ball_threshold_kg"], "ball_mass_kg": row["ball_mass_kg"],
            "nominal_max_draft_m": row["nominal"]["max_draft_m"],
            "nominal_max_drum_deg": row["nominal"]["max_drum_angle_deg"],
            "nominal_max_anchor_deg": row["nominal"]["max_anchor_angle_deg"],
            "nominal_max_radius_m": row["nominal"]["max_wander_radius_m"],
            "stress_max_draft_m": row["stressed"]["max_draft_m"],
            "stress_max_drum_deg": row["stressed"]["max_drum_angle_deg"],
            "stress_max_anchor_deg": row["stressed"]["max_anchor_angle_deg"],
            "stress_max_radius_m": row["stressed"]["max_wander_radius_m"],
            "compromise_score": row.get("compromise_score", ""),
            "pareto": "yes" if row in front else "no",
            "selected": "yes" if row is selected else "no",
        })
    write_csv(RESULTS / "<SOURCE_FILE_REDACTED>", candidate_flat)
    pareto_flat = [row for row in candidate_flat if row["pareto"] == "yes"]
    write_csv(RESULTS / "<SOURCE_FILE_REDACTED>", pareto_flat)

    profile_rows = []
    profile_cases = q1_cases + [q2_initial, q2_recommended, worst_radius]
    profile_labels = ["q1_w12", "q1_w24", "q2_initial", "q2_recommended", "q3_worst_radius"]
    for label, case in zip(profile_labels, profile_cases):
        for index, (x, z, component) in enumerate(chain_profile(case)):
            profile_rows.append({"case": label, "point": index, "x_m": x, "z_m": z, "component": component})
    write_csv(RESULTS / "<SOURCE_FILE_REDACTED>", profile_rows)

    traceability = [
        {"requirement": "Q1 component angles", "variables": "pipe_1_deg..drum_deg", "result_file": "<SOURCE_FILE_REDACTED>", "paper_section": "7.1"},
        {"requirement": "Q1 chain shape", "variables": "x_m,z_m,chain_state", "result_file": "<SOURCE_FILE_REDACTED>;<SOURCE_FILE_REDACTED>", "paper_section": "7.1"},
        {"requirement": "Q1 draft and wander", "variables": "draft_m,wander_radius_m,wander_area_m2", "result_file": "<SOURCE_FILE_REDACTED>", "paper_section": "7.1"},
        {"requirement": "Q2 36 m/s and ball adjustment", "variables": "continuous_threshold_kg,angles,anchor angle", "result_file": "<SOURCE_FILE_REDACTED>;<SOURCE_FILE_REDACTED>", "paper_section": "7.2"},
        {"requirement": "Q3 robust design", "variables": "chain type/link count/length/ball mass", "result_file": "<SOURCE_FILE_REDACTED>", "paper_section": "7.3"},
        {"requirement": "Q3 different conditions", "variables": "33-scenario response grid (calm non-directional state excluded)", "result_file": "<SOURCE_FILE_REDACTED>", "paper_section": "7.3"},
        {"requirement": "validation and robustness", "variables": "residuals/quadrature/sensitivity", "result_file": "<SOURCE_FILE_REDACTED>;<SOURCE_FILE_REDACTED>", "paper_section": "8"},
    ]
    write_csv(RESULTS / "<SOURCE_FILE_REDACTED>", traceability)

    evidence = [
        {"claim": "deterministic rerun", "evidence_layer": "execution", "status": "needs_review", "evidence": "filled after two-run hash comparison"},
        {"claim": "equilibrium equations solved", "evidence_layer": "model_internal", "status": validation_status, "evidence": "<SOURCE_FILE_REDACTED> residual bounds"},
        {"claim": "selected Q3 design meets stated model constraints", "evidence_layer": "model_internal", "status": "pass" if all(case_constraint_ratio(c) <= 1.0 + 1e-8 for c in q3_stress_cases) else "fail", "evidence": "10% stress envelope"},
        {"claim": "real-sea external validity", "evidence_layer": "external", "status": "needs_review", "evidence": "no wave/field data; chain drag geometry unavailable"},
        {"claim": "competition PDF formatting", "evidence_layer": "document", "status": "needs_review", "evidence": "requires successful compilation and visual page inspection"},
    ]
    write_csv(RESULTS / "<SOURCE_FILE_REDACTED>", evidence)

    q3_nominal_metrics = metrics(q3_cases)
    q3_stress_metrics = metrics(q3_stress_cases)
    key_results = {
        "constants": {
            "g_m_s2": G,
            "rho_water_kg_m3": RHO_WATER,
            "rho_steel_kg_m3": RHO_STEEL,
            "wind_coefficient": WIND_COEFF,
            "current_coefficient": CURRENT_COEFF,
        },
        "q1": {case["scenario"]["id"]: flatten_case(case, case["scenario"]["id"]) for case in q1_cases},
        "q2": {
            "continuous_minimum_ball_mass_kg": q2_threshold,
            "recommended_ball_mass_kg": q2_recommended_mass,
            "recommended_ball_submerged_effective_mass_kg": q2_recommended_mass * (1.0 - RHO_WATER / BALL_DENSITY),
            "recommended_ball_submerged_weight_n": ball_weight(q2_recommended_mass),
            "initial": flatten_case(q2_initial, "initial"),
            "recommended": flatten_case(q2_recommended, "recommended"),
        },
        "q3": {
            "selected_design": {
                "chain_type": selected["chain_type"],
                "link_count": selected["link_count"],
                "chain_length_m": selected["chain_length_m"],
                "chain_dry_mass_kg": selected["chain_dry_mass_kg"],
                "ball_mass_kg": selected["ball_mass_kg"],
                "ball_submerged_effective_mass_kg": selected["ball_mass_kg"] * (1.0 - RHO_WATER / BALL_DENSITY),
                "ball_submerged_weight_n": ball_weight(selected["ball_mass_kg"]),
                "selection_rule": "equal-weight Euclidean distance on fixed natural scales: draft/2 m, drum angle/5 deg, radius/20 m",
                "screening_horizontal_factor": 1.10,
            },
            "nominal_33_case_metrics": q3_nominal_metrics,
            "stress_3_depth_metrics": q3_stress_metrics,
            "worst_drum_case": flatten_case(worst_drum, worst_drum["scenario"]["id"]),
            "worst_anchor_case": flatten_case(worst_anchor, worst_anchor["scenario"]["id"]),
            "worst_radius_case": flatten_case(worst_radius, worst_radius["scenario"]["id"]),
            "feasible_candidates": len(candidate_rows),
            "pareto_candidates": len(front),
        },
        "validation": {"status": validation_status, "cases": validation_rows},
    }
    write_json(RESULTS / "key_results.json", key_results)
    write_json(RESULTS / "validation.json", {"status": validation_status, "criteria": {
        "force_residual_abs_n": 1.0e-6,
        "moment_residual_abs_nm": 1.0e-6,
        "geometry_residual_abs_m": 1.0e-8,
        "quadrature_endpoint_abs_m": 1.0e-7,
    }, "cases": validation_rows})

    q1_series = []
    for label, case in zip(("Q1 wind 12", "Q1 wind 24"), q1_cases):
        q1_series.append({"label": label, "points": [(x, z) for x, z, _ in chain_profile(case)],
                          "color": COLORS[len(q1_series)]})
    emit_plot("q1_chain_profiles", q1_series, "Horizontal distance from anchor (m)",
              "Height above seabed (m)", "Question 1 mooring profiles")

    emit_plot("q2_ball_adjustment", [
        {"label": "Drum angle", "points": [(r["ball_mass_kg"], r["drum_angle_deg"]) for r in q2_sweep], "color": COLORS[0]},
        {"label": "Anchor angle", "points": [(r["ball_mass_kg"], r["anchor_angle_deg"]) for r in q2_sweep], "color": COLORS[1]},
    ], "Ball mass (kg)", "Angle (degree)", "Question 2 ball-mass adjustment",
        refs=[(5.0, "drum limit 5 deg"), (16.0, "anchor limit 16 deg")])

    pareto_series = []
    for idx, chain_type in enumerate(CHAIN_TYPES):
        pts = [(r["nominal_max_radius_m"], r["nominal_max_draft_m"]) for r in pareto_flat if r["chain_type"] == chain_type]
        if pts:
            pareto_series.append({"label": "Type " + chain_type, "points": pts, "color": COLORS[idx]})
    pareto_series.append({
        "label": "Selected",
        "points": [(selected["nominal"]["max_wander_radius_m"], selected["nominal"]["max_draft_m"])],
        "color": "#000000",
    })
    emit_plot("q3_pareto", pareto_series, "Worst wander radius (m)", "Worst draft (m)",
              "Question 3 Pareto-feasible designs", scatter=True)

    depth_series = []
    for depth, color in zip((16.0, 18.0, 20.0), COLORS):
        pts = []
        subset = [c for c in q3_cases if c["scenario"]["depth_m"] == depth]
        subset.sort(key=lambda c: c["total_horizontal_force_n"])
        for c in subset:
            pts.append((c["total_horizontal_force_n"], c["drum_angle_deg"]))
        depth_series.append({"label": "Depth %.0f m" % depth, "points": pts, "color": color})
    emit_plot("q3_envelope", depth_series, "Resolved horizontal load (N)", "Drum angle (degree)",
              "Selected design response envelope", refs=[(5.0, "drum limit 5 deg")], scatter=True)

    # Machine-readable TeX macros are the sole source for key rounded paper numbers.
    macros = [
        "%% Generated by code/solve.py; do not edit manually.",
        "\\newcommand{\\QOneTwelveDraft}{%.3f}" % q1_cases[0]["draft_m"],
        "\\newcommand{\\QOneTwelveDrum}{%.2f}" % q1_cases[0]["drum_angle_deg"],
        "\\newcommand{\\QOneTwelveRadius}{%.2f}" % q1_cases[0]["wander_radius_m"],
        "\\newcommand{\\QOneTwentyFourDraft}{%.3f}" % q1_cases[1]["draft_m"],
        "\\newcommand{\\QOneTwentyFourDrum}{%.2f}" % q1_cases[1]["drum_angle_deg"],
        "\\newcommand{\\QOneTwentyFourRadius}{%.2f}" % q1_cases[1]["wander_radius_m"],
        "\\newcommand{\\QTwoInitialDrum}{%.2f}" % q2_initial["drum_angle_deg"],
        "\\newcommand{\\QTwoInitialAnchor}{%.2f}" % q2_initial["chain"]["anchor_angle_deg"],
        "\\newcommand{\\QTwoBallThreshold}{%.1f}" % q2_threshold,
        "\\newcommand{\\QTwoBallRecommended}{%.0f}" % q2_recommended_mass,
        "\\newcommand{\\QTwoBallSubmergedWeight}{%.2f}" % (ball_weight(q2_recommended_mass) / 1000.0),
        "\\newcommand{\\QTwoFinalDrum}{%.2f}" % q2_recommended["drum_angle_deg"],
        "\\newcommand{\\QTwoFinalAnchor}{%.2f}" % q2_recommended["chain"]["anchor_angle_deg"],
        "\\newcommand{\\QThreeChainType}{%s}" % selected["chain_type"],
        "\\newcommand{\\QThreeLinkCount}{%d}" % selected["link_count"],
        "\\newcommand{\\QThreeChainLength}{%.3f}" % selected["chain_length_m"],
        "\\newcommand{\\QThreeBallMass}{%.0f}" % selected["ball_mass_kg"],
        "\\newcommand{\\QThreeBallSubmergedWeight}{%.2f}" % (ball_weight(selected["ball_mass_kg"]) / 1000.0),
        "\\newcommand{\\QThreeWorstDraft}{%.3f}" % q3_nominal_metrics["max_draft_m"],
        "\\newcommand{\\QThreeWorstDrum}{%.2f}" % q3_nominal_metrics["max_drum_angle_deg"],
        "\\newcommand{\\QThreeWorstAnchor}{%.2f}" % q3_nominal_metrics["max_anchor_angle_deg"],
        "\\newcommand{\\QThreeWorstRadius}{%.2f}" % q3_nominal_metrics["max_wander_radius_m"],
        "\\newcommand{\\QThreeStressDrum}{%.2f}" % q3_stress_metrics["max_drum_angle_deg"],
        "\\newcommand{\\QThreeStressAnchor}{%.2f}" % q3_stress_metrics["max_anchor_angle_deg"],
    ]
    (RESULTS / "paper_numbers.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")

    q1_table = [
        "%% Generated by code/solve.py; do not edit manually.",
        "\\begin{tabular}{crrrrrrrr}",
        "\\toprule",
        "Wind & Pipe 1 & Pipe 2 & Pipe 3 & Pipe 4 & Drum & Draft & Radius & Anchor \\\\",
        "(m/s) & (deg) & (deg) & (deg) & (deg) & (deg) & (m) & (m) & (deg) \\\\",
        "\\midrule",
    ]
    for case in q1_cases:
        angles = {m["name"]: m["angle_deg"] for m in case["members"]}
        q1_table.append(
            "%.0f & %.3f & %.3f & %.3f & %.3f & %.3f & %.3f & %.3f & %.3f \\\\" % (
                case["scenario"]["wind_m_s"], angles["pipe_1"], angles["pipe_2"],
                angles["pipe_3"], angles["pipe_4"], angles["drum"], case["draft_m"],
                case["wander_radius_m"], case["chain"]["anchor_angle_deg"],
            )
        )
    q1_table.extend(["\\bottomrule", "\\end{tabular}"])
    (RESULTS / "q1_table.tex").write_text("\n".join(q1_table) + "\n", encoding="utf-8")

    q2_table = [
        "%% Generated by code/solve.py; do not edit manually.",
        "\\begin{tabular}{lrrrrrr}",
        "\\toprule",
        "Design & Ball (kg) & Drum (deg) & Anchor (deg) & Draft (m) & Radius (m) & State \\\\",
        "\\midrule",
        "Initial & 1200 & %.3f & %.3f & %.3f & %.3f & suspended \\\\" % (
            q2_initial["drum_angle_deg"], q2_initial["chain"]["anchor_angle_deg"],
            q2_initial["draft_m"], q2_initial["wander_radius_m"],
        ),
        "Adjusted & %.0f & %.3f & %.3f & %.3f & %.3f & suspended \\\\" % (
            q2_recommended_mass, q2_recommended["drum_angle_deg"],
            q2_recommended["chain"]["anchor_angle_deg"], q2_recommended["draft_m"],
            q2_recommended["wander_radius_m"],
        ),
        "\\bottomrule",
        "\\end{tabular}",
    ]
    (RESULTS / "q2_table.tex").write_text("\n".join(q2_table) + "\n", encoding="utf-8")

    representative_ids = {
        "Q3-D16-W36-C150", "Q3-D18-W00-C150", "Q3-D18-W36-C000",
        "Q3-D18-W36-C150", "Q3-D20-W36-C150",
    }
    q3_table = [
        "%% Generated by code/solve.py; do not edit manually.",
        "\\begin{tabular}{rrrrrrrr}",
        "\\toprule",
        "Depth & Wind & Current & Drum & Anchor & Draft & Radius & State \\\\",
        "(m) & (m/s) & (m/s) & (deg) & (deg) & (m) & (m) & \\\\",
        "\\midrule",
    ]
    for case in q3_cases:
        if case["scenario"]["id"] not in representative_ids:
            continue
        state = "contact" if case["chain"]["state"] == "seabed_contact" else "suspended"
        q3_table.append(
            "%.0f & %.0f & %.2f & %.3f & %.3f & %.3f & %.3f & %s \\\\" % (
                case["scenario"]["depth_m"], case["scenario"]["wind_m_s"],
                case["scenario"]["current_m_s"], case["drum_angle_deg"],
                case["chain"]["anchor_angle_deg"], case["draft_m"],
                case["wander_radius_m"], state,
            )
        )
    q3_table.extend(["\\bottomrule", "\\end{tabular}"])
    (RESULTS / "q3_table.tex").write_text("\n".join(q3_table) + "\n", encoding="utf-8")

    manifest_files = sorted(
        [p for p in RESULTS.iterdir() if p.is_file() and p.name != "generated-manifest.json"]
        + [p for p in FIGURES.iterdir() if p.is_file()]
    )
    manifest = []
    for path in manifest_files:
        manifest.append({
            "path": path.relative_to(ROOT).as_posix(),
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "bytes": path.stat().st_size,
        })
    write_json(RESULTS / "generated-manifest.json", {"files": manifest})

    print(json.dumps({
        "status": "pass" if validation_status == "pass" else "fail",
        "q2_recommended_ball_mass_kg": q2_recommended_mass,
        "q3_selected_design": selected_design,
        "q3_selected_link_count": selected["link_count"],
        "validation": validation_status,
        "generated_files": len(manifest) + 1,
    }, ensure_ascii=False, sort_keys=True))


if __name__ == "__main__":
    main()
