"""Verify artifacts, record/compare deterministic hashes, and update evidence status."""

from __future__ import annotations

import argparse
from hashlib import sha256
import json
import math
from pathlib import Path
import subprocess
import sys
from typing import Any

from PIL import Image
import yaml


ALLOWED_STATUSES = {"pass", "fail", "needs_review"}
NON_PAYLOAD_RESULT_FILES = {
    "rerun-baseline.json",
    "verification.json",
}


def hash_file(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_json(path: Path, value: Any) -> None:
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def core_artifacts(workspace: Path) -> list[Path]:
    results = [
        path
        for path in sorted((workspace / "results").iterdir())
        if path.is_file() and path.name not in NON_PAYLOAD_RESULT_FILES
    ]
    figures = sorted((workspace / "figures").glob("*.png"))
    return results + figures


def artifact_manifest(workspace: Path) -> dict[str, Any]:
    files = {}
    for path in core_artifacts(workspace):
        relative = path.relative_to(workspace).as_posix()
        files[relative] = {"sha256": hash_file(path), "size_bytes": path.stat().st_size}
    return {
        "status": "needs_review",
        "scope": (
            "all files generated by run_all.py under results/ and figures/; "
            "only the verifier's self-referential rerun-baseline.json and verification.json are excluded"
        ),
        "file_count": len(files),
        "files": files,
    }


def check_status_fields(value: Any, path: str = "root") -> list[str]:
    errors: list[str] = []
    if isinstance(value, dict):
        for key, item in value.items():
            key_path = f"{path}.{key}"
            judgement_keys = {
                "status",
                "overall_status",
                "artifact_checks_status",
                "full_rerun_status",
                "external_validity_status",
                "completion_status",
            }
            if key in judgement_keys and isinstance(item, str):
                if item not in ALLOWED_STATUSES:
                    errors.append(f"{key_path}={item!r}")
            errors.extend(check_status_fields(item, key_path))
    elif isinstance(value, list):
        for index, item in enumerate(value):
            errors.extend(check_status_fields(item, f"{path}[{index}]"))
    return errors


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def nearly_equal(left: float, right: float, tolerance: float = 1e-10) -> bool:
    return math.isfinite(left) and math.isfinite(right) and abs(left - right) <= tolerance


def perform_checks(workspace: Path) -> list[dict[str, Any]]:
    checks: list[dict[str, Any]] = []
    required = [
        "problem-analysis.md",
        "data-audit.md",
        "assumptions.yaml",
        "variables.yaml",
        "model-selection.md",
        "solution-report.yaml",
        "reproducibility.yaml",
        "code/model.py",
        "code/run_all.py",
        "code/verify_outputs.py",
        "code/test_model.py",
        "results/problem1-summary.json",
        "results/problem2-summary.json",
        "results/problem3-summary.json",
        "results/validation.json",
        "results/<SOURCE_FILE_REDACTED>",
        "results/provenance.json",
        "figures/<SOURCE_FILE_REDACTED>",
        "figures/<SOURCE_FILE_REDACTED>",
        "figures/<SOURCE_FILE_REDACTED>",
        "paper/main.tex",
        "paper/paper.md",
    ]
    missing = [relative for relative in required if not (workspace / relative).is_file()]
    checks.append(
        {
            "check": "required artifacts exist",
            "status": "pass" if not missing else "fail",
            "details": {"missing": missing},
        }
    )

    yaml_values: dict[str, Any] = {}
    yaml_errors = []
    for relative in ("assumptions.yaml", "variables.yaml", "solution-report.yaml", "reproducibility.yaml"):
        try:
            yaml_values[relative] = yaml.safe_load(
                (workspace / relative).read_text(encoding="utf-8")
            )
        except Exception as error:  # pragma: no cover - evidence path
            yaml_errors.append(f"{relative}: {error}")
    checks.append(
        {
            "check": "YAML parses",
            "status": "pass" if not yaml_errors else "fail",
            "details": {"errors": yaml_errors},
        }
    )

    status_errors = []
    for relative, value in yaml_values.items():
        status_errors.extend(check_status_fields(value, relative))
    for relative in (
        "results/data-audit.json",
        "results/validation.json",
        "results/problem2-summary.json",
        "results/problem3-summary.json",
        "results/provenance.json",
    ):
        if (workspace / relative).is_file():
            status_errors.extend(check_status_fields(load_json(workspace / relative), relative))
    checks.append(
        {
            "check": "automatic status vocabulary",
            "status": "pass" if not status_errors else "fail",
            "details": {"invalid_status_fields": status_errors},
        }
    )

    manifest_errors = []
    for item in load_json(workspace / "results" / "input-manifest.json"):
        path = workspace / item["relative_path"]
        if not path.is_file():
            manifest_errors.append(f"missing {item['relative_path']}")
        elif hash_file(path) != item["sha256"]:
            manifest_errors.append(f"hash mismatch {item['relative_path']}")
    checks.append(
        {
            "check": "input SHA-256 manifest",
            "status": "pass" if not manifest_errors else "fail",
            "details": {"errors": manifest_errors},
        }
    )

    p1 = load_json(workspace / "results" / "problem1-summary.json")
    p2 = load_json(workspace / "results" / "problem2-summary.json")
    p3 = load_json(workspace / "results" / "problem3-summary.json")
    validation = load_json(workspace / "results" / "validation.json")
    numerical_errors = []
    if abs(p1["holding"]["100_mpa"]["metrics_20s_to_30s"]["mean_mpa"] - 100.0) > 0.1:
        numerical_errors.append("Problem 1 100 MPa holding mean outside 0.1 MPa")
    if abs(p1["holding"]["150_mpa"]["metrics_20s_to_30s"]["mean_mpa"] - 150.0) > 0.1:
        numerical_errors.append("Problem 1 150 MPa holding mean outside 0.1 MPa")
    for item in p1["transitions"]:
        mean = item["hold_evaluation_500ms"]["mean_mpa"]
        if abs(mean - 150.0) > 0.1:
            numerical_errors.append(f"Transition {item['transition_ms']} ms post-hold mean")
    omega_interval = p2.get("omega_interval_rad_per_ms", [])
    if len(omega_interval) != 2 or not omega_interval[0] < omega_interval[1]:
        numerical_errors.append("Problem 2 structural omega interval is invalid")
    for name, case in p2.get("structural_cases", {}).items():
        aggregate = case.get("phase_aggregate", {})
        if aggregate.get("status") != "pass":
            numerical_errors.append(f"Problem 2 {name} phase-ensemble status is not pass")
        if abs(float(aggregate.get("mean_of_phase_means_mpa", math.inf)) - 100.0) > 0.2:
            numerical_errors.append(f"Problem 2 {name} long-run mean outside 0.2 MPa")
    best_phase = min(p3["phase_comparison"], key=lambda row: row["evaluation_rmse_mpa"])
    if best_phase["second_injector_offset_ms"] != 50.0:
        numerical_errors.append("50 ms is not the best tested injector phase")
    reference = p3["conditional_reference_scenario"]
    if reference["metrics"]["peak_to_peak_mpa"] >= p3["economy_scheme"]["metrics"]["peak_to_peak_mpa"]:
        numerical_errors.append("Conditional constrained scheme does not improve peak-to-peak pressure")
    control = reference["relief_control"]
    dwell = reference["dwell_statistics"]
    required_dwell = min(control["min_open_ms"], control["min_closed_ms"])
    if dwell["minimum_dwell_ms"] + 1e-9 < required_dwell:
        numerical_errors.append("Conditional relief scenario violates its minimum dwell")
    if validation["convergence"]["overall_status"] == "fail":
        numerical_errors.append("Event-aware time-step convergence contains a fail")
    if validation["mass_balance"]["status"] != "pass":
        numerical_errors.append("Physical mass-balance validation is not pass")
    checks.append(
        {
            "check": "numerical acceptance criteria",
            "status": "pass" if not numerical_errors else "fail",
            "details": {"errors": numerical_errors},
        }
    )

    regression = subprocess.run(
        [sys.executable, "code/test_model.py"],
        cwd=workspace,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    checks.append(
        {
            "check": "audit-finding unit and counterexample regressions",
            "status": "pass" if regression.returncode == 0 else "fail",
            "details": {
                "exit_code": regression.returncode,
                "stdout_tail": regression.stdout[-2000:],
                "stderr_tail": regression.stderr[-2000:],
            },
        }
    )

    figure_errors = []
    for path in sorted((workspace / "figures").glob("*.png")):
        try:
            if path.stat().st_size < 1000:
                raise ValueError("file too small")
            with Image.open(path) as image:
                image.verify()
        except Exception as error:  # pragma: no cover - evidence path
            figure_errors.append(f"{path.name}: {error}")
    checks.append(
        {
            "check": "PNG figures decode",
            "status": "pass" if not figure_errors else "fail",
            "details": {"errors": figure_errors},
        }
    )

    paper_values = load_json(workspace / "results" / "paper-values.json")
    markdown = (workspace / "paper" / "paper.md").read_text(encoding="utf-8")
    expected_strings = [
        f"{paper_values['p1_tau_100_ms']:.5f}",
        f"{paper_values['p1_tau_150_ms']:.5f}",
        f"{paper_values['p2_omega_lower_rad_per_ms']:.6f}",
        f"{paper_values['p2_omega_upper_rad_per_ms']:.6f}",
        f"{paper_values['p2_rpm_lower']:.2f}",
        f"{paper_values['p2_rpm_upper']:.2f}",
        f"{paper_values['p3_economy_rpm']:.2f}",
        f"{paper_values['p3_conditional_ptp_mpa']:.3f}",
        f"{paper_values['p3_relief_ratio']:.2f}",
    ]
    paper_errors = [text for text in expected_strings if text not in markdown]
    tex = (workspace / "results" / "paper-values.tex").read_text(encoding="utf-8")
    for key in ("p2_omega_lower_rad_per_ms", "p2_omega_upper_rad_per_ms"):
        if f"{{{paper_values[key]:.5f}}}" not in tex:
            paper_errors.append(f"generated TeX {key} macro")
    if "103 MPa" in markdown or "103\\,MPa" in markdown:
        paper_errors.append("removed unexecuted 103 MPa safety override claim")
    checks.append(
        {
            "check": "paper key numbers trace to generated values",
            "status": "pass" if not paper_errors else "fail",
            "details": {"missing_expected_strings": paper_errors},
        }
    )

    report = yaml_values.get("solution-report.yaml", {})
    report_errors = []
    comparisons = [
        (report.get("key_results", {}).get("problem_1", {}).get("hold_100_open_ms"), paper_values["p1_tau_100_ms"]),
        (
            report.get("key_results", {}).get("problem_2", {}).get("omega_interval_rad_per_ms", [None, None])[0],
            paper_values["p2_omega_lower_rad_per_ms"],
        ),
        (
            report.get("key_results", {}).get("problem_2", {}).get("omega_interval_rad_per_ms", [None, None])[1],
            paper_values["p2_omega_upper_rad_per_ms"],
        ),
        (
            report.get("key_results", {}).get("problem_3", {}).get("conditional_peak_to_peak_mpa"),
            paper_values["p3_conditional_ptp_mpa"],
        ),
    ]
    for left, right in comparisons:
        if left is None or not nearly_equal(float(left), float(right)):
            report_errors.append(f"solution-report value {left!r} != {right!r}")
    checks.append(
        {
            "check": "solution-report key-number consistency",
            "status": "pass" if not report_errors else "fail",
            "details": {"errors": report_errors},
        }
    )

    provenance = load_json(workspace / "results" / "provenance.json")
    retrieval = load_json(workspace / "retrieval-log.json")
    ledger_ids = {item["id"] for item in provenance.get("cards", [])}
    retrieval_ids = {item["id"] for item in retrieval.get("cards", [])}
    report_ids = set(report.get("training_memory", {}).get("cards", {}))
    provenance_errors = []
    if not ledger_ids or ledger_ids != retrieval_ids or ledger_ids != report_ids:
        provenance_errors.append(
            f"card ID sets differ: ledger={sorted(ledger_ids)}, retrieval={sorted(retrieval_ids)}, report={sorted(report_ids)}"
        )
    for item in provenance.get("cards", []):
        path = workspace / item["relative_path"]
        if not path.is_file() or hash_file(path) != item["sha256"]:
            provenance_errors.append(f"card hash mismatch: {item.get('id')}")
    checks.append(
        {
            "check": "canonical training-memory provenance ledger",
            "status": "pass" if not provenance_errors else "fail",
            "details": {"errors": provenance_errors},
        }
    )
    return checks


def compare_manifest(workspace: Path, baseline: dict[str, Any]) -> dict[str, Any]:
    current = artifact_manifest(workspace)
    before = baseline["files"]
    after = current["files"]
    missing = sorted(set(before) - set(after))
    added = sorted(set(after) - set(before))
    changed = sorted(
        path for path in set(before) & set(after) if before[path]["sha256"] != after[path]["sha256"]
    )
    return {
        "status": "pass" if not (missing or added or changed) else "fail",
        "compared_file_count": len(before),
        "missing": missing,
        "added": added,
        "changed": changed,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workspace", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--record-manifest", action="store_true")
    parser.add_argument("--compare-workspace", type=Path)
    args = parser.parse_args()
    if args.record_manifest and args.compare_workspace is not None:
        parser.error("--record-manifest and --compare-workspace are mutually exclusive")
    workspace = args.workspace.resolve()
    results_dir = workspace / "results"
    baseline_path = results_dir / "rerun-baseline.json"

    checks = perform_checks(workspace)
    check_status = "fail" if any(item["status"] == "fail" for item in checks) else "pass"
    rerun_status = "needs_review"
    comparison: dict[str, Any] = {
        "status": "needs_review",
        "reason": "No second-run comparison performed in this invocation.",
    }

    if args.record_manifest:
        manifest = artifact_manifest(workspace)
        write_json(baseline_path, manifest)
        comparison = {
            "status": "needs_review",
            "recorded_file_count": manifest["file_count"],
            "reason": "Baseline recorded; run code/run_all.py again, then verify without flag.",
        }
    elif args.compare_workspace is not None:
        other_workspace = args.compare_workspace.resolve()
        comparison = compare_manifest(workspace, artifact_manifest(other_workspace))
        comparison["comparison_mode"] = "cross_workspace_generated_payload"
        comparison["other_workspace"] = str(other_workspace)
        rerun_status = comparison["status"]
    elif baseline_path.is_file():
        comparison = compare_manifest(workspace, load_json(baseline_path))
        rerun_status = comparison["status"]

    overall = "fail" if check_status == "fail" or rerun_status == "fail" else "needs_review"
    verification = {
        "overall_status": overall,
        "artifact_checks_status": check_status,
        "full_rerun_status": rerun_status,
        "checks": checks,
        "rerun_comparison": comparison,
        "external_validity_status": "needs_review",
        "note": (
            "Overall remains needs_review because deterministic reproduction and model-internal "
            "checks do not establish experimental external validity."
        ),
    }
    write_json(results_dir / "verification.json", verification)
    if check_status == "fail" or rerun_status == "fail":
        print("[FAIL] output verification failed")
        return 1
    if args.record_manifest:
        print("[NEEDS_REVIEW] baseline recorded; perform a full rerun")
    elif rerun_status == "pass":
        print("[PASS] declared generated payload matches the comparison run")
    else:
        print("[NEEDS_REVIEW] artifact checks pass; rerun comparison not yet available")
    return 0


if __name__ == "__main__":
    sys.exit(main())
